algoritmo "Imprimindo os valores do Vetor"
// Função : Ajudar na chamada da sala de aula
// Autor :  eu
// Data : 13/12/2025
// Seção de Declarações
var
alunos: vetor[1..4] de caractere
cont: inteiro
inicio
// Seção de Comandos
alunos[1]<- "João da Silva"
alunos[2]<- "Carlos Moura"
alunos[3]<- "Maria de Jesus"
alunos[4]<- "Paulo Jóia"
escreval("Os nomes dos alunos são:")
para cont de 1 ate 4 faca
   escreval(alunos[cont])
fimpara
fimalgoritmo
